//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitorsCounter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisitorsCounter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Visitors Counter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonCloseText {
            get {
                return ResourceManager.GetString("ButtonCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonResetText {
            get {
                return ResourceManager.GetString("ButtonResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptionConfirm {
            get {
                return ResourceManager.GetString("CaptionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure want to reset counters? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageConfirmReset {
            get {
                return ResourceManager.GetString("MessageConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10-19 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title10 {
            get {
                return ResourceManager.GetString("Title10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   20-29 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title20 {
            get {
                return ResourceManager.GetString("Title20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   30-39 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title30 {
            get {
                return ResourceManager.GetString("Title30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   40-49 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title40 {
            get {
                return ResourceManager.GetString("Title40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50-59 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title50 {
            get {
                return ResourceManager.GetString("Title50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   60-69 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title60 {
            get {
                return ResourceManager.GetString("Title60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   70-79 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title70 {
            get {
                return ResourceManager.GetString("Title70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   80-89 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title80 {
            get {
                return ResourceManager.GetString("Title80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   90-99 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title90 {
            get {
                return ResourceManager.GetString("Title90", resourceCulture);
            }
        }
    }
}
